version: 2
jobs:
  build:
    
    working_directory: ~/apache-poi-implementation

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: apache-poi-implementation-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: apache-poi-implementation-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/apache-poi-implementation-0.0.1-SNAPSHOT.jar
